# yaml-language-server: $schema=controller_config_schema.json
# Suitable for a AKAI APC mini

channels:
- id_code: 48
  x: 0
- id_code: 49
  x: 1
- id_code: 50
  x: 2
- id_code: 51
  x: 3
- id_code: 52
  x: 4
- id_code: 53
  x: 5
- id_code: 54
  x: 6
- id_code: 55
  x: 7
device:
  input_id: 1
  output_id: 4
keys:
- id_code: 0
  x: 0
  y: 0
- id_code: 1
  x: 1
  y: 0
- id_code: 2
  x: 2
  y: 0
- id_code: 3
  x: 3
  y: 0
- id_code: 4
  x: 4
  y: 0
- id_code: 5
  x: 5
  y: 0
- id_code: 6
  x: 6
  y: 0
- id_code: 7
  x: 7
  y: 0
- id_code: 8
  x: 0
  y: 1
- id_code: 9
  x: 1
  y: 1
- id_code: 10
  x: 2
  y: 1
- id_code: 11
  x: 3
  y: 1
- id_code: 12
  x: 4
  y: 1
- id_code: 13
  x: 5
  y: 1
- id_code: 14
  x: 6
  y: 1
- id_code: 15
  x: 7
  y: 1
- id_code: 16
  x: 0
  y: 2
- id_code: 17
  x: 1
  y: 2
- id_code: 18
  x: 2
  y: 2
- id_code: 19
  x: 3
  y: 2
- id_code: 20
  x: 4
  y: 2
- id_code: 21
  x: 5
  y: 2
- id_code: 22
  x: 6
  y: 2
- id_code: 23
  x: 7
  y: 2
- id_code: 24
  x: 0
  y: 3
- id_code: 25
  x: 1
  y: 3
- id_code: 26
  x: 2
  y: 3
- id_code: 27
  x: 3
  y: 3
- id_code: 28
  x: 4
  y: 3
- id_code: 29
  x: 5
  y: 3
- id_code: 30
  x: 6
  y: 3
- id_code: 31
  x: 7
  y: 3
- id_code: 32
  x: 0
  y: 4
- id_code: 33
  x: 1
  y: 4
- id_code: 34
  x: 2
  y: 4
- id_code: 35
  x: 3
  y: 4
- id_code: 36
  x: 4
  y: 4
- id_code: 37
  x: 5
  y: 4
- id_code: 38
  x: 6
  y: 4
- id_code: 39
  x: 7
  y: 4
- id_code: 40
  x: 0
  y: 5
- id_code: 41
  x: 1
  y: 5
- id_code: 42
  x: 2
  y: 5
- id_code: 43
  x: 3
  y: 5
- id_code: 44
  x: 4
  y: 5
- id_code: 45
  x: 5
  y: 5
- id_code: 46
  x: 6
  y: 5
- id_code: 47
  x: 7
  y: 5
- id_code: 48
  x: 0
  y: 6
- id_code: 49
  x: 1
  y: 6
- id_code: 50
  x: 2
  y: 6
- id_code: 51
  x: 3
  y: 6
- id_code: 52
  x: 4
  y: 6
- id_code: 53
  x: 5
  y: 6
- id_code: 54
  x: 6
  y: 6
- id_code: 55
  x: 7
  y: 6
- id_code: 56
  x: 0
  y: 7
- id_code: 57
  x: 1
  y: 7
- id_code: 58
  x: 2
  y: 7
- id_code: 59
  x: 3
  y: 7
- id_code: 60
  x: 4
  y: 7
- id_code: 61
  x: 5
  y: 7
- id_code: 62
  x: 6
  y: 7
- id_code: 63
  x: 7
  y: 7
master_channel:
  id_code: 56
master_stop:
  id_code: 119
